import type { ISession } from "./types";

export function generateMockSessions(): Array<ISession> {
  const partners = [
    { id: "user1", name: "Sarah Johnson", avatar: "/placeholder-avatar.jpg" },
    { id: "user2", name: "Mike Chen", avatar: "/placeholder-avatar.jpg" },
    { id: "user3", name: "Maria Garcia", avatar: "/placeholder-avatar.jpg" },
    { id: "user4", name: "David Martinez", avatar: "/placeholder-avatar.jpg" },
    { id: "user5", name: "Emma Wilson", avatar: "/placeholder-avatar.jpg" },
    { id: "user6", name: "James Brown", avatar: "/placeholder-avatar.jpg" },
    { id: "user7", name: "Alex Thompson", avatar: "/placeholder-avatar.jpg" },
    { id: "user8", name: "Sophie Lee", avatar: "/placeholder-avatar.jpg" },
  ];

  const descriptions = [
    "Learning advanced techniques and best practices",
    "Teaching fundamentals and core concepts",
    "Practice and hands-on exercises",
    "Interactive learning session",
    "Building practical skills together",
    "Exploring new concepts and methods",
    "Structured lesson with clear objectives",
    "Collaborative learning experience",
  ];

  const objectives = [
    ["Master core concepts", "Practice exercises", "Review progress"],
    ["Learn fundamentals", "Build projects", "Get feedback"],
    ["Improve skills", "Practice techniques", "Track improvement"],
    ["Understand basics", "Apply knowledge", "Complete exercises"],
    ["Explore topics", "Hands-on practice", "Review outcomes"],
  ];

  const completedTimes = [
    "Dec 20, 2:00 PM",
    "Dec 18, 10:00 AM",
    "Dec 15, 4:00 PM",
    "Dec 12, 11:00 AM",
    "Dec 10, 3:00 PM",
  ];

  const sessions: Array<ISession> = [
    // Active sessions
    {
      id: 1,
      type: "Learning",
      skill: "Photography",
      partner: partners[0],
      status: "active",
      scheduledTime: "Today, 2:00 PM",
      duration: 60,
      location: "online",
      meetingLink: "https://meet.example.com/abc123",
      progress: 45,
      description: descriptions[0],
      objectives: objectives[0],
    },
    {
      id: 2,
      type: "Teaching",
      skill: "Web Development",
      partner: partners[1],
      status: "active",
      scheduledTime: "Today, 4:00 PM",
      duration: 90,
      location: "online",
      meetingLink: "https://meet.example.com/xyz789",
      progress: 30,
      description: descriptions[1],
      objectives: objectives[1],
    },
    // Scheduled sessions
    {
      id: 3,
      type: "Learning",
      skill: "Spanish",
      partner: partners[2],
      status: "scheduled",
      scheduledTime: "Tomorrow, 10:00 AM",
      duration: 45,
      location: "online",
      description: descriptions[2],
      objectives: objectives[2],
    },
    {
      id: 4,
      type: "Teaching",
      skill: "Graphic Design",
      partner: partners[3],
      status: "scheduled",
      scheduledTime: "Dec 28, 4:00 PM",
      duration: 60,
      location: "online",
      description: descriptions[3],
      objectives: objectives[3],
    },
    {
      id: 5,
      type: "Learning",
      skill: "Korean Language",
      partner: partners[4],
      status: "scheduled",
      scheduledTime: "Dec 29, 11:00 AM",
      duration: 50,
      location: "online",
      description: descriptions[4],
      objectives: objectives[4],
    },
    {
      id: 6,
      type: "Teaching",
      skill: "Cooking",
      partner: partners[5],
      status: "scheduled",
      scheduledTime: "Dec 30, 3:00 PM",
      duration: 75,
      location: "in-person",
      description: descriptions[5],
      objectives: objectives[0],
    },
    {
      id: 7,
      type: "Learning",
      skill: "Guitar",
      partner: partners[6],
      status: "scheduled",
      scheduledTime: "Jan 2, 9:00 AM",
      duration: 60,
      location: "online",
      description: descriptions[6],
      objectives: objectives[1],
    },
    {
      id: 8,
      type: "Teaching",
      skill: "Yoga",
      partner: partners[7],
      status: "scheduled",
      scheduledTime: "Jan 3, 2:00 PM",
      duration: 45,
      location: "in-person",
      description: descriptions[7],
      objectives: objectives[2],
    },
    // Completed sessions
    {
      id: 9,
      type: "Learning",
      skill: "Data Science",
      partner: partners[0],
      status: "completed",
      scheduledTime: completedTimes[0],
      duration: 90,
      location: "online",
      description: descriptions[0],
      objectives: objectives[0],
      completedAt: completedTimes[0],
      rating: 5,
    },
    {
      id: 10,
      type: "Teaching",
      skill: "React Development",
      partner: partners[1],
      status: "completed",
      scheduledTime: completedTimes[1],
      duration: 60,
      location: "online",
      description: descriptions[1],
      objectives: objectives[1],
      completedAt: completedTimes[1],
      rating: 4,
    },
    {
      id: 11,
      type: "Learning",
      skill: "UI/UX Design",
      partner: partners[2],
      status: "completed",
      scheduledTime: completedTimes[2],
      duration: 75,
      location: "online",
      description: descriptions[2],
      objectives: objectives[2],
      completedAt: completedTimes[2],
      rating: 5,
    },
    {
      id: 12,
      type: "Teaching",
      skill: "Python Programming",
      partner: partners[3],
      status: "completed",
      scheduledTime: completedTimes[3],
      duration: 60,
      location: "online",
      description: descriptions[3],
      objectives: objectives[3],
      completedAt: completedTimes[3],
      rating: 4,
    },
    {
      id: 13,
      type: "Learning",
      skill: "Music Theory",
      partner: partners[4],
      status: "completed",
      scheduledTime: completedTimes[4],
      duration: 45,
      location: "online",
      description: descriptions[4],
      objectives: objectives[4],
      completedAt: completedTimes[4],
      rating: 5,
    },
  ];

  return sessions;
}
